// Экспорт shared кода
export * from './types';
export * from './utils/utils';
export * from './constants/promotions';
export * from './constants/services';
export * from './constants/rooms';
export * from './constants/faqs';
export * from './hooks/scrollToTop';
export * from './hooks/use-mobile';
export * from './hooks/use-toast';
export * from './hooks/useYandexReviews'; 